###
GET http://localhost:3000/ 

###
GET http://localhost:3000/data/

###
GET http://localhost:3000/index 


### 
POST http://localhost:3000/data
Content-Type: application/json

{
    "id": "3",
    "forename": "New",
    "surname": "User"
}


### post json
POST http://localhost:3000/data
Content-Type: application/json

{
    "id": "10",
    "forename": "New",
    "surname": "User"
}

### test unsupported type
POST http://localhost:3000/data
Content-Type: text/csv

{
    "id": "3",
    "forename": "Roy",
    "surname": "User"
}


###
DELETE http://localhost:3000/data/14

### put json
PUT http://localhost:3000/data/90
Content-Type: application/json

{
    //"id": "10",
    "forename": "Roy",
    "surname": "User"
}

### put unsupported type
PUT http://localhost:3000/data/100
Content-Type: text/csv

{
    //"id": "10",
    "forename": "New",
    "surname": "User"
}

###
POST http://localhost:3000/data/search
Content-Type: application/json

{
  "forename": "Roy"
}

###
POST http://localhost:3000/data/search
Content-Type: application/json

{
  "surname": "User"
}

###
POST http://localhost:3000/data/search
Content-Type: application/json

{
  "forename": "Not in list"
}



### test data without token
GET http://localhost:3000/data



### test login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user",
    "password": "password"
}


### test login using wrong data
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "not user",
    "password": "not password"
}


### test data with token
GET http://localhost:3000/data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpYXQiOjE3NjM2NjA3MDcsImV4cCI6MTc2MzY2NDMwN30.3d9ZHGx2NpxtwaxRukoajfzz5MaCrZI8dchxzuTiG1U
Accept: application/json






